- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    apache:
      user: ttskch
      document_root: /Users/ttskch/.ghq
    dotfiles:
      clone_command: "ghq get -p ttskch/dotfiles"
      symlink_command: "cd ~/.ghq/github.com/ttskch/dotfiles && sh symlink.sh"

    homebrew_taps:
      - caskroom/cask
      - dteoh/sqa
      - homebrew/php
      - homebrew/apache
      - sanemat/font

    homebrew_packages:
      - { name: ansible }
      - { name: antiword }
      - { name: coreutils }
      - { name: docker-clean }
      - { name: diff-so-fancy }
      - { name: exiftool }
      - { name: figlet }
      - { name: ffmpeg, install_options: with-tools }
      - { name: git }
      - { name: ghq }
      - { name: graphviz }
      - { name: heroku }
      - { name: htop-osx }
      - { name: hub }
      - { name: imagemagick }
      - { name: iproute2mac }
      - { name: jq }
      - { name: lastpass-cli }
      - { name: mas }
      - { name: mysql }
      - { name: nkf }
      - { name: node }
      - { name: node, state: unlinked }   # unlink node7
      - { name: node@6 }
      - { name: openssl }
      - { name: p7zip }
      - { name: packer }
      - { name: pandoc }
      - { name: peco }
      - { name: php71, state: unlinked }   # unlink existent php71
      - { name: php56, install_options: "with-httpd24,enable-shmop" }
      - { name: php56-imagick, install_options: build-from-source }
      - { name: php56-intl }
      - { name: php56-opcache }
      - { name: php56-apcu }
      - { name: php56-mcrypt }
      - { name: php56-xdebug }
      - { name: php56-xhprof }
      - { name: php56, state: unlinked }   # unlink php56
      - { name: php71, install_options: "with-httpd24,enable-shmop" }
      - { name: php71-imagick, install_options: build-from-source }
      - { name: php71-intl }
      - { name: php71-opcache }
      - { name: php71-apcu }
      - { name: php71-apcu-bc }
      - { name: php71-mcrypt }
      - { name: php71-xdebug }
      # - { name: php71-xhprof }
      - { name: php71 }   # re-link php71
      - { name: phpunit }
      - { name: python }
      - { name: python3 }
      - { name: reattach-to-user-namespace }
      - { name: rename }
      - { name: ruby }
      - { name: sbt }
      - { name: scala }
      - { name: sendemail }
      - { name: sl }
      - { name: sqlite }
      - { name: ssh-copy-id }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: unrar }
      - { name: wget }
      - { name: youtube-dl }
      - { name: zsh }
      - { name: zsh-completions }
      # php dependent packages
      - { name: boris }
      - { name: composer }
      - { name: deployer }

    php_configs:
      - { regexp: '^;?(max_execution_time) *=.*$',            replace: '\1 = 0' }
      - { regexp: '^;?(max_input_time) *=.*$',                replace: '\1 = -1' }
      - { regexp: '^;?(memory_limit) *=.*$',                  replace: '\1 = 512M' }
      - { regexp: '^;?(date.timezone) *=.*$',                 replace: '\1 = Asia/Tokyo' }
      - { regexp: '^;?(mbstring.language) *=.*$',             replace: '\1 = Japanese' }
      - { regexp: '^;?(mysql.default_socket) *=.*$',          replace: '\1 = /private/tmp/mysql.sock' }
      - { regexp: '^;?(pdo_mysql.default_socket) *=.*$',      replace: '\1 = /private/tmp/mysql.sock' }
      - { regexp: '^;?(zend_extension *= *opcache.so)',       replace: ';\1' }   # just comment out
      - { regexp: '^;?(always_populate_raw_post_data) *=.*$', replace: '\1 = -1' }   # tentative for php70
      - { regexp: '^;?(auto_detect_line_endings) *=.*$',      replace: '\1 = On' }

    homebrew_cask_packages:
      - alfred
      - appcleaner
      - astah-community
      - atom
      - avast-mac-security
      - bitbar
      - caffeine
      - cooviewer
      - dash
      - docker
      - dropbox
      - eclipse-java
      - filezilla
      - firefox
      - flash-player
      - google-backup-and-sync
      - google-chrome
      - google-drive-file-stream
      - grammarly
      - gyazo
      - handbrake
      - intellij-idea-ce
      - java
      # - karabiner
      - kindle
      - libreoffice
      - insomnia
      - insomniax
      - phpstorm
      - pingendo
      - plex-media-server
      - qr-journal
      - reaper
      - ripit
      - sequel-pro
      - slack
      - slowquitapps
      - skitch
      - skype
      - soundflower
      - spectacle
      - transmission
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
      - vlc
      - xmind
      # quicklook related
      - qlstephen
      - qlcolorcode
      - qlmarkdown
      - qlimagesize
      - betterzipql
      - quicklook-csv
      - quicklook-json

    mas_packages:
      - { name: GarageBand, id: 408980954 }
      - { name: iMovie, id: 408981434 }
      - { name: "iMovie 9.0.9", id: 408981434 }
      - { name: Keynote, id: 409183694 }
      - { name: LadioCast, id: 411213048 }
      - { name: LINE, id: 539883307 }
      - { name: "Memory Clean", id: 451444120 }
      - { name: "Tomato One", id: 907364780 }
      - { name: Twitter, id: 409789998 }
      - { name: "WinArchiver Lite", id: 414855915 }
      - { name: Xcode, id: 497799835 }

    npm_packages:
      - { name: "@angular/cli" }
      - { name: bower }
      - { name: coffee-script }
      - { name: grunt }
      - { name: grunt-cli }
      - { name: gulp }
      - { name: karma }
      - { name: less }
      - { name: localtunnel }
      - { name: nativefier }
      - { name: typescript }
      - { name: typings }
      - { name: yarn }

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf

  tasks:
    # brew tap
    - name: install taps of homebrew
      homebrew_tap: tap="{{ item }}" state=present
      with_items: "{{ homebrew_taps }}"
      tags:
        - brew

    # brew update
    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - brew

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: "{{ homebrew_packages }}"
      tags:
        - brew

    - name: link node@6 forcely
      shell: brew link node@6 --force
      register: ret
      changed_when: '"Already linked" not in ret.stdout'
      tags:
        - brew

    # brew cask install
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item }}" state=present
      with_items: "{{ homebrew_cask_packages }}"
      ignore_errors: true
      tags:
        - cask

    # mas install
    - name: install mas (App Store) packages
      shell: mas install "{{ item.id }}"
      with_items: "{{ mas_packages }}"
      register: ret
      changed_when: '"already installed" not in ret.stdout'
      tags:
        - mas

    # mas upgrade
    - name: upgrade all mas (App Store) packages
      shell: mas upgrade
      register: ret
      changed_when: '"Everything is up-to-date" not in ret.stdout'
      tags:
        - mas

    # npm -g install
    - name: install npm packages
      npm: name="{{ item.name }}" state="{{ item.state|default('latest') }}" version="{{ item.version|default() }}" global=yes
      with_items: "{{ npm_packages }}"
      tags:
        - npm

    # gem install bundler
    - name: install bundler
      gem: name="bundler" state="latest"
      tags:
        - gem

    # install oh-my-zsh
    - name: install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: ~/.oh-my-zsh
      tags:
        zsh
    - name: install zsh-completions
      file: src=/usr/local/share/zsh-completions dest=~/.oh-my-zsh/custom/plugins/zsh-completions state=link
      tags:
        zsh

    # install Ricty font
    - name: install xquartz
      homebrew_cask: name=xquartz
      tags:
        ricty
    - name: install ricty
      homebrew: name=ricty
      tags:
        ricty
    - name: copy generated font file
      shell: "cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/"
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache
      tags:
        ricty

    # configure apache
    - name: backup default DocumentRoot directory
      shell: mv /usr/local/var/www/htdocs /usr/local/var/www/htdocs.bak removes=/usr/local/var/www/htdocs creates=/usr/local/var/www/htdocs.bak
      tags:
        apache
    - name: put symlink to DocumentRoot
      file: src="{{ apache.document_root }}" dest=/usr/local/var/www/htdocs state=link force=yes
      tags:
        apache
    - name: configure httpd.conf (replace)
      replace: dest=/usr/local/etc/apache2/2.4/httpd.conf regexp="{{ item.regexp }}" replace="{{ item.replace }}"
      with_items:
        - { regexp: '^( *Listen) .*$',                                  replace: '\1 80' }
        - { regexp: '^( *User) .*$',                                    replace: '\1 {{ apache.user }}' }
        - { regexp: '^( *DirectoryIndex) .*$',                          replace: '\1 index.php index.html' }
        - { regexp: '^( *)# *(AddHandler cgi-script .cgi).*$',          replace: '\1\2' }   # just comment in
        - { regexp: '^( *)# *(LoadModule rewrite_module +.*)$',         replace: '\1\2' }   # just comment in
        - { regexp: '^LoadModule +php\d_module +/usr/local/Cellar/.+\n', replace: '' }   # remove the line already exists
      tags:
        - apache
    - name: configure httd.conf (insert)
      lineinfile: dest=/usr/local/etc/apache2/2.4/httpd.conf insertafter="{{ item.insertafter }}" line="{{ item.line }}"
      with_items:
        - { insertafter: "LoadModule rewrite_module",         line: "#LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so" }
        - { insertafter: "LoadModule php5_module",            line: "LoadModule php7_module /usr/local/opt/php71/libexec/apache2/libphp7.so" }
        - { insertafter: '^#ServerName ',                     line: "ServerName localhost:80" }
        - { insertafter: '^ *AddType ',                       line: "    AddType application/x-httpd-php .php" }
        - { insertafter: '^ *# *Include .+httpd-vhosts.conf', line: "Include /usr/local/etc/apache2/2.4/extra/httpd-vhosts.my.conf" }
      tags:
        - apache
    - name: create httpd-vhosts.conf
      copy: src=templates/httpd-vhosts.my.conf dest=/usr/local/etc/apache2/2.4/extra/httpd-vhosts.my.conf
      args:
        force: no
      tags:
        - apache

    # configure php56, php71
    - name: configure php.ini of php56
      replace: dest=/usr/local/etc/php/5.6/php.ini regexp="{{ item.regexp }}" replace="{{ item.replace }}"
      with_items: "{{ php_configs }}"
      tags:
        - php
    - name: configure php.ini of php71
      replace: dest=/usr/local/etc/php/7.1/php.ini regexp="{{ item.regexp }}" replace="{{ item.replace }}"
      with_items: "{{ php_configs }}"
      tags:
        - php

    # configure xdebug
    - name: configure ext-xdebug.ini
      copy: src=templates/ext-xdebug.my.ini dest=/usr/local/etc/php/7.1/conf.d/ext-xdebug.my.ini
      tags:
        - php

    # configure xhprof
    # - name: make xhprof dir in DocumentRoot
    #   file: dest=/usr/local/var/www/htdocs/xhprof state=directory
    #   tags:
    #     - php
    # - name: symlink xhprof into DocumentRoot
    #   file: src="{{ item.src }}" dest="{{ item.dest }}" state=link
    #   with_items:
    #     - { src: /usr/local/opt/php71-xhprof/xhprof_html, dest: /usr/local/var/www/htdocs/xhprof/xhprof_html }
    #     - { src: /usr/local/opt/php71-xhprof/xhprof_lib, dest: /usr/local/var/www/htdocs/xhprof/xhprof_lib }
    #   tags:
    #     - php
    # - name: put a snippet file into xhprof dir
    #   copy: src=templates/xhprof.snippet dest=/usr/local/var/www/htdocs/xhprof/xhprof.snippet
    #   tags:
    #     - php

    # install hirak/prestissimo
    - name: install hirak/prestissimo
      composer: command=require arguments=hirak/prestissimo working_dir=~/.composer
      tags:
        composer

    # configure mysql
    - name: chown mysql directory
      file: path=/usr/local/var/mysql owner=_mysql group=_mysql recurse=yes
      become: yes
      become_method: sudo
      tags:
        mysql

    # install dotfiles
    - name: git clone dotfiles
      shell: "{{ dotfiles.clone_command }}"
      register: ret
      when: dotfiles.clone_command
      changed_when: 'ret.rc != 0 or "exists" not in ret.stdout'
      tags:
        - dotfiles
    - name: symlink dotfiles
      shell: "{{ dotfiles.symlink_command }}"
      when: ret|changed
      tags:
        - dotfiles
